apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devx-175
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/andrii-hryniv/dora-project.git'
    path: devx-175
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: prometheus
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

