apiVersion: v2
name: devx-175
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: kube-prometheus-stack
  version: "51.0.2"
  repository: "https://prometheus-community.github.io/helm-charts"

